### PR TITLE
Reformat code, fix typos, and use apt instead of apt-get

### PR DESCRIPTION
**Pull request by Kazevic**
apt-get is long deprecated. The same goes for the "align" element. I also did a line wrapping where it was EXTREMELY necessary.

### CODE REVIEW

**Comment by Castro-Fidel** [comment]
В Альтах нет `apt`, а есть `apt-get`. (Пакетный менеджер apt-rpm)

**Comment by Kazevic** [comment]
Sorry, I didn't know about that. Those changes have been reverted now, so can it be merged?

**Comment by Castro-Fidel** [comment]
Крайний вопрос, заxем затронуты svg файлы?
Без них приму PR.

**Comment by Kazevic** [comment]
The only thing that has changed about the SVGs is the formatting. The images are the same.

**Comment by Castro-Fidel** [comment]
> The only thing that has changed about the SVGs is the formatting. The images are the same.

Не надо этого делать. Пусть svg останутся такими как и были.

**Comment by Kazevic** [comment]
Sorry to keep you waiting. I think there's nothing left to do now.

**Pull request merged**
